title: Academic website template
author: needawebguy.com
email:
description: >-
  Website template for Academic conferences
baseurl: "/template"
# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page" # this ensures all content renders with layouts/page.html
      templates:
        - page
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      templates:
        - post
collections:
    posts:
      output: true
markdown: kramdown
jekyll-archives:
  enabled: all
  layout: "archive"
pugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
permalink: pretty
