baseurl:
# Build settings
defaults:
  - scope:
        path: "" # an empty string here means all files in the project
    values:
        layout: "page" # this ensures all content renders with layouts/default.html
gems:
    - jekyll-menus
    - jekyll-feed
incremental: true
