---
new_page_extension: md
auto_deploy: true
admin_path: admin/
webhook_url: 
collections:
- path: ''
  label: Pages
  create: all
- path: _posts
  label: Posts
  create: all
upload_dir: uploads
public_path: "/template/uploads"
front_matter_path: "/template/uploads"
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
