---
new_page_extension: md
auto_deploy: true
admin_path: admin/
webhook_url:
sections:
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page
- type: jekyll-posts
  label: Posts
  create: all
  label: Blog
  templates:
  - post
upload_dir: uploads
public_path: "/template/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
